-- Seed data: 46 EngageEngine client GBPs
-- Source: business.google.com/u/1/locations extracted 2026-03-20
-- Run: wrangler d1 execute gbp-intelligence-db --file=scripts/seed.sql

INSERT OR IGNORE INTO clients (name, address, status, active, notes) VALUES
  ('Artists for Africa', 'United States', 'active', 1, NULL),
  ('Atlantic Building Materials', '321 Community Rd, Blythewood, SC 29016', 'active', 1, NULL),
  ('Austin Drilling & Well Repair Inc', '14786 C R Koon Hwy, Newberry, SC 29108', 'active', 1, NULL),
  ('Austin Drilling Inc', '3830 Hwy 321, West Columbia, SC 29172', 'active', 1, NULL),
  ('Blue Marlin', '1200 Lincoln St, Columbia, SC 29201', 'active', 1, NULL),
  ('Brabham Fence Company', '119 Farm Rd, Summerville, SC 29485', 'active', 1, NULL),
  ('Brabham Fence Company', '2800 William H Tuller Drive, Columbia, SC 29205', 'active', 1, NULL),
  ('Carolina Stone Craftsman', '2010 Chapin Rd, Chapin, SC 29036', 'active', 1, NULL),
  ('CENTA Medical Group', '157 Corley Mill Rd, Lexington, SC 29072', 'active', 1, NULL),
  ('CENTA Medical Group', '9 Medical Park Dr #510, Columbia, SC 29203', 'active', 1, NULL),
  ('CENTA Medical Group (duplicate)', '9 Medical Park Dr #510, Columbia, SC 29203', 'duplicate', 0, 'Duplicate'),
  ('Cricket Newman Designs', '2005 N Beltline Blvd Suite 6, Columbia, SC 29204', 'active', 1, NULL),
  ('Crystal Clean Janitorial', 'Columbia/Lexington/Chapin, SC', 'active', 1, NULL),
  ('DNB Electric Inc.', '310 Cedarcrest Dr, Lexington, SC 29072', 'active', 1, NULL),
  ('Donen Davis Plastic Surgery', '1850 Laurel St B, Columbia, SC 29201', 'active', 1, NULL),
  ('Floor Pro Cleaning & Restoration', '107 Vera Rd, Lexington, SC 29072', 'active', 1, NULL),
  ('Furniture on Sunset', '2250 Sunset Blvd Suite H, West Columbia, SC 29169', 'closed', 0, 'Marked as closed from Google — confirm with client'),
  ('Genesis Pro Painters', 'Columbia/Lexington/Chapin, SC', 'suspended', 0, 'Suspended'),
  ('Icebox Cryotherapy Columbia', '4609 Forest Drive Bldg E Suite 3, Columbia, SC 29206', 'active', 1, NULL),
  ('Macon Metal Roofing Inc', '7789 Hawkinsville Rd, Macon, GA 31216', 'active', 1, NULL),
  ('Marketing Performance, LLC', 'United States', 'active', 1, NULL),
  ('Midland''s Construction', 'Irmo/Cayce + 5 other areas, SC', 'unverified', 0, 'Verification required'),
  ('Midlands Landscape and Lawn', '1612 North Lake Drive, Lexington, SC 29072', 'active', 1, NULL),
  ('Mike''s Painting & Sandblasting', '1015 Acline Ave, Myrtle Beach, SC 29577', 'active', 1, NULL),
  ('Nature''s Best Lawn & Landscape', 'Irmo/Elgin + 5 other areas, SC', 'active', 1, NULL),
  ('Palmetto Equipment Sales & Services', '6920 Pennington Rd Suite A, Columbia, SC 29209', 'active', 1, NULL),
  ('Preferred Home Inspections, Inc', 'Irmo/Cayce + 10 other areas, SC', 'active', 1, NULL),
  ('Pucci Commercial Properties', '720 Old Clemson Rd Suite E, Columbia, SC 29229', 'unverified', 0, 'Verification required'),
  ('Rhino Linings of Lexington', '108-A White Oak Lane, Lexington, SC 29073', 'active', 1, NULL),
  ('Rytech Restoration of the Midlands', '1310 Haviland Circle STE B, Columbia, SC 29210', 'duplicate', 0, 'Duplicate'),
  ('Sandra E. Hennies, M.Ed., LMFT', '906 Burwell Lane, Columbia, SC 29205', 'duplicate', 0, 'Duplicate'),
  ('Signature Catering', '991 First Street South, Columbia, SC 29209', 'active', 1, NULL),
  ('Signature Catering (duplicate)', '991 1st St S, Columbia, SC 29209', 'duplicate', 0, 'Duplicate'),
  ('Smith-Built Metal Building & Supplies', '6945 Albany Hwy, Dawson, GA 39842', 'active', 1, NULL),
  ('SmithBuilt Metal Roofing', '802 Rosewood Drive, Columbia, SC 29201', 'active', 1, NULL),
  ('Smith-Built Metals (duplicate)', '6945 Albany Hwy, Dawson, GA 39842', 'duplicate', 0, 'Duplicate'),
  ('Soda City Dentistry', '1801 Charleston Hwy, Cayce, SC 29033', 'active', 1, NULL),
  ('Stormy Plumbing', '1308 Boiling Springs Rd, Lexington, SC 29073', 'active', 1, NULL),
  ('StripeWide Inc.', '1824 Airport Blvd, Cayce, SC 29033', 'active', 1, NULL),
  ('Sub Station II', '928 Main St, Columbia, SC 29201', 'closed', 0, 'Permanently closed'),
  ('Superior Plumbing & Gas', '3610 Landmark Dr Suite F, Columbia, SC 29204', 'active', 1, NULL),
  ('The Fritz Pet Resort and Spa', '432 Ermine Rd, West Columbia, SC 29170', 'active', 1, NULL),
  ('The Guttermen', '3631 Delree St, West Columbia, SC 29170', 'active', 1, NULL),
  ('The Red Shirt Guys Roofing', '720 Old Clemson Rd ste b, Columbia, SC 29229', 'active', 1, NULL),
  ('Township Auditorium', '1703 Taylor St, Columbia, SC 29201', 'active', 1, NULL),
  ('Whetzel''s Automotive', '2017 Augusta Rd, West Columbia, SC 29169', 'active', 1, NULL);
